In [1]:
from itertools import batched
import os

import pandas as pd
import numpy as np
import regex

from derwent_api.tsip import SearchByQuery

## AI

API query.

In [2]:
ipcs = SearchByQuery.convert_codes('G06F19/24 OR G06N3 OR G06N5 OR G06N7/02 OR G06N7/04 OR G06N7/06 OR G06N20 OR G06T1/40 OR G16B4/20 OR G16B4/30 OR G16C20/70', 'ipc')
cpcs = SearchByQuery.convert_codes('A61B5/7267 OR G01N33/0034 OR G06F19/24 OR G10H2250/151 OR H04L2025/03464 OR B29C66/965 OR G01N2201/1296 OR G06F19/707 OR G10H2250/311 OR H04N21/4662 OR B29C2945/76979 OR G01S7/417 OR G06F2207/4824 OR G10K2210/3024 OR H04N21/4663 OR B60G2600/1876 OR G05B13/027 OR G06K7/1482 OR G10K2210/3038 OR H04N21/4665 OR B60G2600/1878 OR G05B13/0275 OR G06N3/004 OR G10L25/30 OR H04N21/4666 OR B60G2600/1879 OR G05B13/028 OR G06N3/02 OR G11B20/10518 OR H04Q2213/054 OR E21B2041/0028 OR G05B13/0285 OR G06N3/12 OR H01J2237/30427 OR H04Q2213/13343 OR F02D41/1405 OR G05B13/029 OR G06N5 OR H02P21/0014 OR H04Q2213/343 OR F03D7/046 OR G05B13/0295 OR G06N7 OR H02P23/0018 OR H04R25/507 OR F05B2270/707 OR G05B2219/33002 OR G06N20 OR H03H2017/0208 OR Y10S128/924 OR F05B2270/709 OR G05D1/0088 OR G06N99/005 OR H03H2222/04 OR Y10S128/925 OR F05D2270/707 OR G06F11/1476 OR G06T3/4046 OR H04L25/0254 OR Y10S706 OR F05D2270/709 OR G06F11/2257 OR G06T9/002 OR H04L25/03165 OR F16H2061/0081 OR G06F11/2263 OR G06T2207/20081 OR H04L41/16 OR F16H2061/0084 OR G06F15/18 OR G06T2207/20084 OR H04L45/08 OR G01N29/4481 OR G06F17/16 OR G08B29/186 OR H04L2012/5686', 'cpc')
keywords = SearchByQuery.convert_keywords('ant-colony OR factorization machin* OR high-dimensional* feature* OR particle-swarm* OR bee-colony OR factorisation machin* OR high-dimensional* input* OR pattern-recogni* OR fire-fly OR feature engineer* OR k-means OR policy-gradient method OR adversar* network* OR feature extract* OR kernel learn* OR q-learn* OR artificial*-intelligen* OR feature select* OR latent-variable* OR random-forest* OR association rule OR fuzzy-c OR link* predict* OR recommender system* OR auto-encod* OR fuzzy environment* OR machine intelligen* OR reinforc* learn* OR autonom* comput* OR fuzzy logic* OR machine learn* OR sentiment* analy* OR back-propagat* OR fuzzy number* OR map-reduce OR sparse represent* OR back-propogat* OR fuzzy set* OR memetic algorithm* OR sparse*-code* OR cognitiv* comput* OR fuzzy system* OR multi* label* classif* OR spectral cluster* OR collaborat* filter* OR gaussian mixture model OR multi*-objective* algorithm* OR stochastic*-gradient* OR deep-belief network* OR gaussian process* OR multi*-objective* optim* OR *supervis* learn* OR deep-learn* OR genetic program* OR natural-gradient OR support-vector machine OR differential*-evol* algorithm* OR genetic* algorithm OR neural-turing OR swarm behav* OR dimensional*-reduc* OR high-dimensional* data OR *neural-network* OR swarm intell* OR ensemble-learn* OR high-dimensional* model* OR neuro-morph comput* OR transfer-learn* OR evolution* algorithm* OR high-dimensional* space* OR non-negative matri* factor* OR variation*-infer* OR evolution* comput* OR high-dimensional* system* OR object-recogni* OR vector-machine*')

ai_search = SearchByQuery(
    f'(ic=({ipcs}) OR cpc=({cpcs}) OR abe=({keywords})) AND pd>=(19970101) AND pd<(20180101) NOT ki=(U* OR Y* OR Z*)',
    ['pn', 'pd', 'cdpt', 'cgpt', 'co'],
    size=1000000,
    search_limit=1000000,
    display_limit=1000000,
    list_filter='collapse:derwent-family'
)
ai_patents = ai_search.post()

ai_patents.pn_orig = ai_patents.pn_orig.map(lambda x: x.removesuffix('_'))
for i, batch in enumerate(batched(ai_patents.pn_orig, 30000)):
    with open(f'../.data/derwent/ai/pn/ai_pns_{i}.txt', 'w') as f:
        f.write('\n'.join(pd.unique(batch)))
ai_patents.to_pickle('../.data/derwent/ai/ai_api.pkl')

ai_patents

# of patents: 244772
# of families: 116903

/tmp/ipykernel_928779/525991837.py:21: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  f.write('\n'.join(pd.unique(batch)))

field,id,cdpt_dwpi,cgpt_dwpi,co_dwpi,pd_orig,pn_orig,ref_derwent
0,AR96636A120160120,13,18,"DEERE & CO,,,,",2016-01-20,AR96636A1,US20140277961A120140918
1,AU199951042A_20000207,111,210,"ROVI GUIDES INC,,,,",2000-02-07,AU199951042A,US20170366831A120171221
2,AU200040571A_20001016,528,896,"TIVO INC,,,,",2000-10-16,AU200040571A,US20130294754A120131107
3,AU200120992A_20010703,37,265,"TIVO INC,,,,",2001-07-03,AU200120992A,US9854310B220171226
4,AU200127351A_20010703,861,497,"TIVO INC,,,,",2001-07-03,AU200127351A,US9788049B220171010
...,...,...,...,...,...,...,...
244767,UY35453A_20140530,0,0,",,,,",2014-05-30,UY35453A,None
244768,UY36156A_20160129,0,0,",,,,",2016-01-29,UY36156A,None
244769,UY36576A_20160930,0,0,",,,,",2016-09-30,UY36576A,None
244770,UY36717A_20161130,0,0,",,,,",2016-11-30,UY36717A,None
244771,UY36977A_20170630,0,0,",,,,",2017-06-30,UY36977A,None

Bringing in the fields from the website.

In [8]:
path = '../.data/derwent/ai' 

ai = pd.read_pickle(f'{path}/ai_api.pkl') # These might not run sequentially
ai.rename(columns={'cdpt_dwpi': 'n_backward_citations',
                   'cgpt_dwpi': 'n_forward_citations',
                   'co_dwpi': 'assignee',
                   'pd_orig': 'publication_date',
                   'pn_orig': 'publication_number',
                   'ref_derwent': 'family_root'},
          inplace=True)

dl = []
for f in os.listdir(f'{path}/dl'):
    df = pd.read_excel(f'{path}/dl/{f}', skiprows=1)
    df.rename(columns={'Publication Number': 'publication_number',
                       'IPC Section - DWPI': 'ipc_section',
                       'IPC Class - DWPI': 'ipc_class',
                       'IPC Subclass - DWPI': 'ipc_subclass',
                       'IPC Class Group - DWPI': 'ipc_class_group',
                       'IPC Subgroup - DWPI': 'ipc_subgroup',
                       'Abstract (English)': 'abstract',
                       'Claims Count': 'n_claims',
                       'DWPI Count of Family Members': 'family_size',
                       'Cited Refs - Patent': 'backward_citations',
                       'Strategic Importance': 'strategic_importance',
                       'Probability of Grant': 'p_grant',
                       'Domain Influence': 'domain_influence',
                       'Combined Patent Impact': 'combined_patent_impact'},
              inplace=True)
    dl.append(df)
dl = pd.concat(dl)
dl.dropna(subset=['ipc_class', 'ipc_class_group', 'ipc_section', 'ipc_subclass',
                  'ipc_subgroup', 'abstract', 'n_claims', 'family_size',
                  'strategic_importance', 'p_grant', 'domain_influence',
                  'combined_patent_impact'],
          inplace=True)

dl.abstract = dl.abstract.map(lambda x: regex.sub('\n',
                                                  ' ',
                                                  x,
                                                  flags=regex.IGNORECASE))
dl.ipc_subgroup = dl.ipc_subgroup.map(lambda x: regex.sub(r'\s+\(.*?\)', '', x))

dl.ipc_section = dl.ipc_section.map(lambda x: x.split(', '))
dl.ipc_class = dl.ipc_class.map(lambda x: x.split(', '))
dl.ipc_subclass = dl.ipc_subclass.map(lambda x: x.split(', '))
dl.ipc_class_group = dl.ipc_class_group.map(lambda x: x.split(', '))
dl.ipc_subgroup = dl.ipc_subgroup.map(lambda x: x.split(', '))
dl.backward_citations = dl.backward_citations.map(lambda x: x.split(' | '),
                                                  na_action='ignore')

dl.p_grant = dl.p_grant / 100

ai = pd.merge(ai, dl, on='publication_number')
ai.replace({np.nan: None}, inplace=True)

ai.to_pickle(f'{path}/ai_patents.pkl')

ai

,id,n_backward_citations,n_forward_citations,assignee,publication_date,publication_number,family_root,ipc_class,ipc_class_group,ipc_section,ipc_subclass,ipc_subgroup,abstract,n_claims,family_size,backward_citations,strategic_importance,p_grant,domain_influence,combined_patent_impact
0,AR96636A120160120,13,18,"DEERE & CO,,,,",2016-01-20,AR96636A1,US20140277961A120140918,"[A01, G05]","[A01D0041, A01D0069, G05B0013]","[A, G]","[A01D, G05B]","A01D004100, A01D0041127, A01D006900, G05B001302",System for detecting one of an operating stat...,11.0,11.0,None,1.0,1.0,1.00,1.00
1,AU2006283101A120070301,37,77,"BETH ISRAEL DEACONESS MEDICAL CENT,,,,",2008-03-06,AU2006283101A1,US9844590B220171219,"[A61, C07, C12]","[A61K0048, A61K0031, A61K0038, A61K0039, A61P0...","[A, C]","[A61K, A61P, C07H, C07K, C12N]","A61K004800, A61K00317088, A61K003800, A61K0038...","The present invention relates, in general, to...",12.0,25.0,[WO2005028625A2],1.0,0.0,1.00,1.00
2,AU2006283101B220130307,37,77,"BETH ISRAEL DEACONESS MEDICAL CENT,,,,",2013-03-07,AU2006283101B2,US9844590B220171219,"[A61, C07, C12]","[A61K0048, A61K0031, A61K0038, A61K0039, A61P0...","[A, C]","[A61K, A61P, C07H, C07K, C12N]","A61K004800, A61K00317088, A61K003800, A61K0038...","The present invention relates, in general, t...",8.0,25.0,[WO2005028625A2],1.0,0.0,1.00,1.00
3,AU2009335623A120100715,24,439,"INT BUSINESS MACHINES CORP,,,,",2011-07-28,AU2009335623A1,US8630961B220140114,"[G06, H04, G09]","[G06F0017, G06N0003, G06N0005, G06N0007, G06N0...","[G, H]","[G06F, G06N, H04L, G09B]","G06F001700, G06F001720, G06N000300, G06N000502...","In one aspect, the invention concerns a meth...",40.0,9.0,None,1.0,1.0,1.00,1.00
4,AU2009335623B220120510,24,439,"INT BUSINESS MACHINES CORP,,,,",2012-05-10,AU2009335623B2,US8630961B220140114,"[G06, H04, G09]","[G06F0017, G06N0003, G06N0005, G06N0007, G06N0...","[G, H]","[G06F, G06N, H04L, G09B]","G06F001700, G06F001720, G06N000300, G06N000502...","In one aspect, the invention concerns a meth...",23.0,9.0,None,1.0,1.0,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143504,TWI607387B_20171201,32,52,"IND TECHNOLOGY RES INST,,,,",2017-12-01,TWI607387B,None,[G06],"[G06K0009, G06N0003, G06T0007, G06V0010]",[G],"[G06K, G06N, G06T, G06V]","G06K000900, G06K000932, G06K000946, G06K000962...","A character recognition method is provided, i...",20.0,6.0,"[TWI221587B, US20140363074A1, TWI221587A, TW20...",1.0,1.0,4.64,4.03
143505,TWI607389B_20171201,9,22,"KNERON INC,,,,",2017-12-01,TWI607389B,None,[G06],[G06N0003],[G],[G06N],"G06N000302, G06N000304, G06N0003063",A pooling operation method for convolutional ...,16.0,4.0,"[CN106250863A, CN106203619A, CN106228240A]",1.0,1.0,3.02,2.68
143506,TWI607412B_20171201,19,13,"IND TECHNOLOGY RES INST,,,,",2017-12-01,TWI607412B,None,"[G06, H04]","[G06T0007, H04N0013]","[G, H]","[G06T, H04N]","G06T000700, G06T000760, H04N001302, G06T000700...",Measurement system and method for measuring m...,18.0,4.0,"[TW201346833A, TW201624326A, US20130249901A1, ...",1.0,1.0,2.62,2.35
143507,TWI608369B_20171211,33,12,"IND TECHNOLOGY RES INST,,,,",2017-12-11,TWI608369B,None,"[G01, G06]","[G01N0021, G06F0017, G06K0009, G06N0003, G06T0...",[G],"[G01N, G06F, G06K, G06N, G06T]","G01N002188, G06F001730, G06K000962, G06N000304...","A classification method, a classification mod...",16.0,5.0,"[TW200844429A, TWI456190B, TWI456190A, WO20160...",1.0,1.0,1.81,1.67
143508,TWI609261B_20171221,0,0,"ALIBABA GROUP SERVICES LTD,,,,",2017-12-21,TWI609261B,TW201727558A_20170801,"[G01, G06]","[G01R0031, G06F0011, G06Q0050]",[G],"[G01R, G06F, G06Q]","G01R0031317, G06F001126, G06Q005000, G06Q00500...",The present invention provides an input devic...,6.0,2.0,"[TWI438657B, US20100077260A1, TWI438657A, TW20...",1.0,1.0,1.40,1.34

# CCMT

In [2]:
ccmt_search = SearchByQuery(
    'cpc=(Y02B OR Y02C OR Y02D OR Y02E OR Y02T OR Y04S) AND pd>=(20000101) AND pd<(20200101) NOT ki=(U* OR Y* OR Z*)',
    ['pn', 'pd', 'cdpt', 'cgpt', 'co'],
    size=1000000,
    search_limit=1000000,
    display_limit=1000000,
    list_filter='collapse:derwent-family'
)
ccmt_patents = ccmt_search.post()
ccmt_families = ccmt_patents[ccmt_patents.ref_derwent.isnull()]

print(f'# of patents: {len(pd.unique(ccmt_patents.id))}')
print(f'# of families: {len(pd.unique(ccmt_families.id))}')

for i, batch in enumerate(batched(ccmt_patents.pn_orig, 30000)):
    with open(f'../.data/derwent/ccmt_pns_{i}.txt', 'w') as f:
        f.write('\n'.join(pd.unique(batch)))
ai_patents.to_pickle('../.data/derwent/ccmt_patents.pkl')

ccmt_patents

KeyboardInterrupt:

# Oil

In [4]:
keywords = SearchByQuery.convert_keywords('shale OR kerogen oil OR light oil OR cannel oil OR oghead coal OR alum shale OR stellarite OR albertite OR kerosene shale OR bituminite OR gas coal OR algal coal OR wollongite OR schistes bitumineux OR torbanite OR kukersite OR tight gas OR tight oil OR bakken')
titles = SearchByQuery.convert_keywords('coal mining OR biofuel OR coal tar')

oil_search = SearchByQuery(
    f'(ic=(C10B OR C10G OR E21B OR C09K008) AND ctb=({keywords}) AND ad>=(20000101) AND ad<(20140821)) NOT tie=({titles}) NOT ki=(U* OR Y* OR Z*)',
    ['pn', 'pd', 'cdpt', 'cgpt', 'co'],
    size=1000000,
    search_limit=1000000,
    display_limit=1000000,
    list_filter='collapse:derwent-family'
)
oil_patents = oil_search.post()
oil_families = oil_patents[oil_patents.ref_derwent.isnull()]

print(f'# of patents: {len(pd.unique(oil_patents.id))}')
print(f'# of families: {len(pd.unique(oil_families.id))}')

for i, batch in enumerate(batched(oil_patents.pn_orig, 30000)):
    with open(f'../.data/derwent/oil_pns_{i}.txt', 'w') as f:
        f.write('\n'.join(pd.unique(batch)))
ai_patents.to_pickle('../.data/derwent/oil_patents.pkl')

oil_patents

# of patents: 20222
# of families: 5596

/tmp/ipykernel_919116/1300488300.py:20: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  f.write('\n'.join(pd.unique(batch)))

field,id,cdpt_dwpi,cgpt_dwpi,co_dwpi,pd_orig,pn_orig,ref_derwent
0,AM2655A_20120725,95,4,"RED LEAF RESOURCES INC,,,,",2012-07-25,AM2655A_,IL214554A_20130203
1,AM2656A_20120725,93,10,"RED LEAF RESOURCES INC,,,,",2012-07-25,AM2656A_,US8267481B220120918
2,AM2657A_20120725,103,12,"RED LEAF RESOURCES INC,,,,",2012-07-25,AM2657A_,US20100200467A120100812
3,AM2658A_20120725,98,4,"RED LEAF RESOURCES INC,,,,",2012-07-25,AM2658A_,WO2010093700A220100819
4,AM2659A_20120725,132,18,"RED LEAF RESOURCES INC,,,,",2012-07-25,AM2659A_,US20100200465A120100812
...,...,...,...,...,...,...,...
20217,VN10017500A_20100525,0,0,",,,,",2010-05-25,VN10017500A_,None
20218,VN10017568A_20100927,0,0,",,,,",2010-09-27,VN10017568A_,None
20219,VN33132A_20130325,9,17,"HITACHI LTD,,,,",2013-03-25,VN33132A_,None
20220,ZA200101109B_20010810,0,0,"BAKER HUGHES INC,,,,",2001-08-10,ZA200101109B_,None
20221,ZA200208892B_20030505,17,42,"UNITED WIRE LTD,,,,",2003-05-05,ZA200208892B_,None